### ISSUE TITLE
First blog post not appearing in gh pages

### ISSUE THREAD

**Issue by MonicaUnlimited** [MonicaUnlimited/blognewbie#1]
Hello, my first blog post is not appearing in my gh page - https://monicaunlimited.github.io/blognewbie/
Could someone take a peek at my files/code and let me know what went sideways.  :confused:
Thanks!

**Comment by MonicaUnlimited** [comment]
@AlexChambers 
@jonabc
Alex or Jon, not sure what i did wrong :confused:

**Comment by AlexChambers** [comment]
@MonicaUnlimited looking...

**Comment by jonabc** [comment]
@MonicaUnlimited @AlexChambers :wave: I think it might be the `hacker` theme.

I took a look at it's source - https://github.com/pages-themes/hacker and I don't see anything that would display posts automatically.

Just to check that it's not something in your setup here, what happens if you change the theme to `minima`?  If posts start showing up, then it's does seem related to the `hacker` theme.

**UPDATE** for some deeper background/information, `site.posts` is the code that tells Jekyll and GitHub Pages to find posts from the `_posts` folder.

I searched for `site.posts` in the search bar for [hacker](https://github.com/pages-themes/hacker)  and [nothing was returned](https://github.com/pages-themes/hacker/search?q=site.posts&unscoped_q=site.posts).  Doing the same thing for [minima](https://github.com/jekyll/minima) showed `site.posts` [being used in _layouts/home.html](https://github.com/jekyll/minima/search?q=site.posts&unscoped_q=site.posts).

**Comment by MonicaUnlimited** [comment]
@jonabc  :star:
Thanks for checking.  I will change to minima and see what happens.

**Comment by MonicaUnlimited** [comment]
well well well... i guess minima is the key to blog post.  this issue is resolved. :clap:
i will check my other blog post.
thanks team! :+1:
